//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoservice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoserviceEntities : DbContext
    {
        public AutoserviceEntities()
            : base("name=AutoserviceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoMark> AutoMarks { get; set; }
        public virtual DbSet<AutoModel> AutoModels { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<Spare> Spares { get; set; }
        public virtual DbSet<SpareType> SpareTypes { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
    }
}
