//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autoservice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id { get; set; }
        public int Value { get; set; }
        public string Spare_Vendorcode { get; set; }
        public int Provider_Id { get; set; }
        public int Manufacturer_Id { get; set; }
    
        public virtual Manufacturer ManufacturerSet { get; set; }
        public virtual Provider ProviderSet { get; set; }
        public virtual Spare SpareSet { get; set; }
    }
}
